### PR TITLE
Added deleteGroup method

### PR DESCRIPTION
**Pull request by ffxsam**
This isn't done yet, but I wanted to at least start the PR for discussion. The idea came to me when I saw there were orphaned groups hanging around in my users collection.

### CODE REVIEW

**Comment by ffxsam** [comment]
@alanning Thoughts on this?

**Comment by mitar** [comment]
This is already implemented in v2.0 version. The question is if we want to be further modifying the v1.0 version or should v1.0 be just getting bugfixes from now on. This pull request is not a bug fix.

**Comment by ffxsam** [comment]
Ahh, probably not - it can wait for 2.0. I'll close this PR. Thanks!

**Comment by mitar** [comment]
You can also try to use it, it is in the v2.0 branch.

**Pull request closed without merging**
