### PR TITLE
V2.0

### PR DESCRIPTION
**Pull request by mitar**
Ready for review and merging. Feedback welcome.

I changed the style to use `;` at the end of the lines because otherwise you can have strange bugs. This is the recommended practice.

TODO:
 * [x] update README and other examples
 * [x] explain how to migrate from 1.0 to 2.0
 * [x] document backwards incompatible changes
 * [x] add extra tests for new features
 * [x] add tests for edge cases
 * [x] add tests for migrations
 * [x] add a function to set a role as a subrole
 * [x] add code-comment headers to all functions
 * [ ] publish new http://alanning.github.io/meteor-roles/classes/Roles.html
 * [ ] publish new `flow-router` example app online at http://roles.meteor.com/
 * [ ] configure Travis CI for integration tests

### CODE REVIEW

**Comment by mitar** [comment]
All old tests are passing. All old functionality is there. Groups are renamed to partitions. Partitions are now always used. There are some backwards incompatible changes to make code more secure, especially important for such package (I throw more exceptions when there are invalid inputs to functions, no auto-creation of roles when assigning them).

**Comment by alanning** [comment]
Thanks @mitar !!   I'm working my way through your changes.  

Initial thoughts are all positive.  Awesome work!

Function-wise, it would help me if you could update the usage examples section in the Readme with changes / using the hierarchy.

I have to think further on if there should be a difference between a default partition and a "global" partition (to use the old terminology).

Stylistically semi-colons shouldn't be used in this repo but that's not a big deal.

**Comment by mitar** [comment]
> Function-wise, it would help me if you could update the usage examples section in the Readme with changes / using the hierarchy.

Yes, README is on the todo.

**Comment by mitar** [comment]
BTW, this pull requests is build upon #145 and #146, so it would be great if you could merge them in first.

**Comment by mitar** [comment]
> Stylistically semi-colons shouldn't be used in this repo but that's not a big deal.

Yes, I am proposing to change this. Because for me this is not just a question of style (for other things you choose whatever you see fit), but ending `;` can really change how does parser parse it so for me is beyond just style. It just makes things more robust and predictable. Especially in a security-sensitive libraries I would not go for things without `;` where then two statements can become one and some condition might never be checked.

**Comment by mitar** [comment]
> Function-wise, it would help me if you could update the usage examples section in the Readme with changes / using the hierarchy.

Done. README and examples and API documentation updated.

**Comment by mitar** [comment]
This is done. It has all the functionalities we discussed, examples, updated documentation, and full test suite.

I would recommend that you give me commit access to the repository and I can merge this and help you maintain the package, as I am more familiar with the code now. I can also publish a new package if you give me permissions on the Meteor package. If you give me access also to the `roles.meteor.com`, I can also release new version there. I would also go through all open pull requests and tickets and see which one are still relevant and address them, or close others.

Any feedback welcome.

**Comment by alanning** [comment]
@mitar, thank you!  What a great Christmas present!  :-)

Glad you are interested in joining as a maintainer and I'm happy to have your help.  I'm back at my parent's home for the Christmas holiday now but timing-wise I'd like to review this and get this into production early Jan.

One feature that I will need shortly for my own app is granting users temporary access to certain functionality without forcing them to log in first.  So that will be a great test case to see how the new design handles extension.

I'm looking forward to going through your work!

**Comment by mitar** [comment]
> One feature that I will need shortly for my own app is granting users temporary access to certain functionality without forcing them to log in first. So that will be a great test case to see how the new design handles extension.

Hm, I do not really see an easy way to do so. Maybe rather use something like:
 * https://github.com/artwells/meteor-accounts-guest

**Comment by alanning** [comment]
Thanks for doing the README.  Big help for me.

I merged your PR into this repo's [v2.0](https://github.com/alanning/meteor-roles/tree/v2.0) branch so that we can work on it more there.

I created an [issue](https://github.com/alanning/meteor-roles/issues/165) so we can track discussion of a few things. Not sure if that's the best forum for it but we can try it out.

**Comment by mitar** [comment]
> Not sure if that's the best forum for it but we can try it out.

I prefer discussion in the tickets. So for me is good.

**Comment by mitar** [comment]
Closing this in favor of #165.

**Pull request closed without merging**
